services:
  certbot_dns_cloudflare:
    image: certbot/dns-cloudflare
    volumes:
      - certbot_dns_cloudflare:/etc/letsencrypt
    secrets:
      - source: cloudflare_ini 
        target: /root/cloudflare.ini 
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email ${DOMAIN_EMAIL} 
      --agree-tos
      --no-eff-email
      -n
      -d *.${DOMAIN}
      -d ${DOMAIN}
    deploy:
      restart_policy:
        delay: 300s

  docs:
      image: ghcr.io/mfdebby/mfdebby/docs:${DOCS_VERSION}
      networks:
        - mfdebby-network

  home:
      image: ghcr.io/mfdebby/mfdebby/home:${HOME_VERSION}
      networks:
        - mfdebby-network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - certbot_dns_cloudflare:/etc/letsencrypt
      - reverse-proxy-logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_default_template
        target: /etc/nginx/conf.d/default.conf
    networks:
      - mfdebby-network

  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOZZLE_NO_ANALYTICS=false
    secrets:
      - source: dozzle_users
        target: /data/users.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle:/data
    networks:
      - mfdebby-network

configs:
  nginx_conf:
    external: true
  nginx_default_template:
    external: true

secrets:
  cloudflare_ini:
    external: true
  dozzle_users:
    external: true

volumes:
  certbot_dns_cloudflare:
  reverse-proxy-logs:
  dozzle:

networks:
  mfdebby-network:
    driver: overlay
