services:
  certbot_dns_cloudflare:
    image: certbot/dns-cloudflare
    volumes:
      - certbot_dns_cloudflare:/etc/letsencrypt
    secrets:
      - source: cloudflare_ini 
        target: /root/cloudflare.ini 
    command: >-
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email ${DOMAIN_EMAIL} 
      --agree-tos
      --no-eff-email
      -n
      -d *.${DOMAIN}
      -d ${DOMAIN}
    deploy:
      restart_policy:
        delay: 300s
    env_file:
      - .env

  docs:
      image: ghcr.io/mfdebby/mfdebby/docs:${GIT_COMMIT_HASH}
      networks:
        - mfdebby-network

  home:
      image: ghcr.io/mfdebby/mfdebby/home:${GIT_COMMIT_HASH}
      networks:
        - mfdebby-network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - certbot_dns_cloudflare:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_default_template
        target: /etc/nginx/conf.d/default.conf
    networks:
      - mfdebby-network

configs:
  nginx_conf:
    external: true
  nginx_default_template:
    external: true

secrets:
  cloudflare_ini:
    external: true

volumes:
  certbot_dns_cloudflare:

networks:
  mfdebby-network:
    driver: overlay
